### ISSUE TITLE
分布式哈希一致性如何设置？

### ISSUE THREAD

**Issue by eudore** [pangudashu/memcache#1]
没有哈希一致性相关的介绍，哈希一致性算法导致使用时其他语言时，部分数据无法读取。

**Comment by pangudashu** [comment]
@eudore 不支持与其它语言的client兼容，因为不同语言的数据类型不尽相同，client在实现上没有统一，比如go里面map类型数据，在其它语言里面就是其它的结构（php array、java hashmap……）

**Comment by eudore** [comment]
已解决  fork github.com/bradfitz/gomemcache，然后修改了hash集群。
